Get-Help * | more\                                                                                                                                                                                                                     
Get-Help * | more                                                                                                                                                                                                                      
Get-Help *alias*                                                                                                                                                                                                                       
Get-Alias                                                                                                                                                                                                                              
get-help Get-Command                                                                                                                                                                                                                  
Get-help powershell.exe                                                                                                                                                                                                                
Get-help about_                                                                                                                                                                                                                        
Get-help about_Powershell.exe                                                                                                                                                                                                          
Get-help about_powershell.exe                                                                                                                                                                                                          
Get-help *command*                                                                                                                                                                                                                     
get-command | more                                                                                                                                                                                                                    
get-command -CommandType cmdlet                                                                                                                                                                                                       
get-help  Get-Command -full                                                                                                                                                                                                            
# Get-Help Get-command -Parameter                                                                                                                                                                                                        
# Get-Help Get-command -Parameters                                                                                                                                                                                                       
Get-Help Get-command -Parameter *                                                                                                                                                                                                      
Get-Command -CommandType Cmdlet -Name *service*                                                                                                                                                                                        
Get-Command -Verb stop                                                                                                                                                                                                                 
Start-Process notepad.exe                                                                                                                                                                                                            
Get-Process -Name notepad                                                                                                                                                                                                              
# Start-Process .\notepad.exe                                                                                                                                                                                                            
Get-Process -Name notepad                                                                                                                                                                                                              
Stop-Process 1644                                                                                                                                                                                                                      
Get-ChildItem                                                                                                                                                                                                                          
# Get-ChildItem |Format-Table -name                                                                                                                                                                                                      
Get-ChildItem |Format-Table name                                                                                                                                                                                                       
Get-ChildItem |Format-List                                                                                                                                                                                                             
#  get-command -CommandType Cmdlet -Name )ut*                                                                                                                                                                                            
 get-command -CommandType Cmdlet -Name Out*                                                                                                                                                                                            
Get-Process | Out-GridView                                                                                                                                                                                                             
Get-Process | Out-File                                                                                                                                                                                                                 
Get-Process Out-File -Examples  | more                                                                                                                                                                                                 
Get-Process | Out-File -Examples  | more                                                                                                                                                                                               
Get-Process | Out-File -Example  | more                                                                                                                                                                                                
Get-help  Out-File -Example  | more                                                                                                                                                                                                    
Get-help  Out-File -Examples  | more                                                                                                                                                                                                   
Get-Process | Out-File -FilePath C:/test/procs.txt                                                                                                                                                                                     
Get-Process | Out-File -FilePath C:\test\procs.txt                                                                                                                                                                                     
Get-Process | Out-File -FilePath C:\procs.txt                                                                                                                                                                                          
Get-Content -Path C:\procs.txt                                                                                                                                                                                                         
get-help -get                                                                                                                                                                                                                          
get-help get                                                                                                                                                                                                                           
Get-ChildItem | Format-List * | Out-File -FilePath C:/list.txt                                                                                                                                                                         
get-content -Path C:\list.txt                                                                                                                                                                                                          
"Hello" + "World"                                                                                                                                                                                                                      
"Hello" + 3                                                                                                                                                                                                                            
3 + "Hello"                                                                                                                                                                                                                            
$a =3                                                                                                                                                                                                                                  
3a                                                                                                                                                                                                                                     
$a                                                                                                                                                                                                                                     
$a *= 2                                                                                                                                                                                                                                
$a                                                                                                                                                                                                                                     
clear                                                                                                                                                                                                                                  
3 -eq 4                                                                                                                                                                                                                                
3 -eq 3                                                                                                                                                                                                                                
3 -le 4                                                                                                                                                                                                                                
"Hello Powershell" -match "Power"                                                                                                                                                                                                      
"Hello Powershell" -match "power"                                                                                                                                                                                                      
"Hello Powershell" -replace "Shell"                                                                                                                                                                                                    
"Hello Powershell" -replace "Shell", "Punch"                                                                                                                                                                                           
"lo" -in "Hello Powershell"                                                                                                                                                                                                            
"lo" -in "Hello Powershell","lo"                                                                                                                                                                                                       
1 -in (1,2,3,4)                                                                                                                                                                                                                        
Get-Location                                                                                                                                                                                                                           
Get-Location > C:/loc.txt                                                                                                                                                                                                              
get-content -Path C:\loc.txt                                                                                                                                                                                                           
Get-Location >> C:/loc.txt                                                                                                                                                                                                             
get-content -Path C:\loc.txt                                                                                                                                                                                                           
(1 -le 3) -and (1 -ge 0)                                                                                                                                                                                                               
(1 -le 3) -and (1 -ge 2)                                                                                                                                                                                                               
(1 -le 3) -or (1 -ge 2)                                                                                                                                                                                                                
"Welcome to Powershell Penetration Testers" -split " "                                                                                                                                                                                 
"Welcome to Powershell Penetration Testers" -split "t"                                                                                                                                                                                 
"Welcome to Powershell Penetration Testers" -split "t",3                                                                                                                                                                               
"Welcome to Powershell Penetration Testers" -split "Powershell"                                                                                                                                                                        
"We1","Please" -Join "come"                                                                                                                                                                                                            
3 -is "int"                                                                                                                                                                                                                            
3 -is "string"                                                                                                                                                                                                                         
"3" -is "string"                                                                                                                                                                                                                       
0x12 -as "int"                                                                                                                                                                                                                         
0x12 -as "string"                                                                                                                                                                                                                      
$value = "string" +1                                                                                                                                                                                                                   
$value.GetType()                                                                                                                                                                                                                       
 $str = "This is a string"                                                                                                                                                                                                             
$str.GetType()                                                                                                                                                                                                                         
"Another string: $str"                                                                                                                                                                                                                 
'Another string: $str'                                                                                                                                                                                                                 
clear                                                                                                                                                                                                                                  
@"...                                                                                                                                                                                                                                  
clear                                                                                                                                                                                                                                  
$a = 3.2 +3                                                                                                                                                                                                                            
$a                                                                                                                                                                                                                                     
$a.gettype()                                                                                                                                                                                                                           
[int]$a = 3.2 + 2                                                                                                                                                                                                                      
$a                                                                                                                                                                                                                                     
$a.gettype()                                                                                                                                                                                                                           
$a = 5.2 + 2                                                                                                                                                                                                                           
[int]$a                                                                                                                                                                                                                                
clear                                                                                                                                                                                                                                  
$result = Get-ChildItem                                                                                                                                                                                                                
$result.GetType()                                                                                                                                                                                                                      
$array = 1,2,3                                                                                                                                                                                                                         
$array                                                                                                                                                                                                                                 
$array.length                                                                                                                                                                                                                          
$array[0]                                                                                                                                                                                                                              
$array[1]                                                                                                                                                                                                                              
$array[2]                                                                                                                                                                                                                              
$array = 1,"hi",2.2                                                                                                                                                                                                                    
$array                                                                                                                                                                                                                                 
4emptyarray = @()                                                                                                                                                                                                                      
$emptyarray = @()                                                                                                                                                                                                                      
$emptyarray                                                                                                                                                                                                                            
$emptyarray.GetType()                                                                                                                                                                                                                  
if ( 1 - gt 0) { "one"} else {"something"}                                                                                                                                                                                             
if (1 -gt 0) { "one"} else {"something"}                                                                                                                                                                                               
if (1 -gt 3) { "one"} else {"something"}                                                                                                                                                                                               
if (((Get-Process).Count) -gt 40) {"Too many processes"} else {"OK"}                                                                                                                                                                   
clear                                                                                                                                                                                                                                  
history                                                                                                                                                                                                                                
switch (1) {1 {"one"} 2 {"Two"}}                                                                                                                                                                                                       
switch (11) {1 {"one"} 2 {"Two"} default {"Default"}}                                                                                                                                                                                  
switch -wildcard ('abc') {a* {"A"} *b* {"B"} c* {"C"}}                                                                                                                                                                                 
switch -Regex -File C:\test\WindowsUpdate.log {'Validating'{$_}}                                                                                                                                                                       
$count = 3                                                                                                                                                                                                                             
while ($count -ge 0)...                                                                                                                                                                                                                
while ($count -ge 0)...                                                                                                                                                                                                                
while ($count -ge 0)...                                                                                                                                                                                                                
while ($count -ge 0)...                                                                                                                                                                                                                
$count = 3                                                                                                                                                                                                                             
while ($count -ge 0)...                                                                                                                                                                                                                
$procs = Get-Process                                                                                                                                                                                                                   
foreach ($proc in $procs){...                                                                                                                                                                                                          
clear                                                                                                                                                                                                                                  
Get-Process | ForEach-Object {$_.Name}                                                                                                                                                                                                 
clear                                                                                                                                                                                                                                  
Get-ChildItem C:/ |Where-Object {$_.Name -match "txt"}                                                                                                                                                                                 
Get-Process | ForEach-Object {$_.Path}                                                                                                                                                                                                 
clear                                                                                                                                                                                                                                  
 ise                                                                                                                                                                                                                                   
cd /                                                                                                                                                                                                                                   
& '.\Users\hfaka\Desktop\pentester Powershell\HelloWorld.ps1'                                                                                                                                                                          
Get-ExecutionPolicy                                                                                                                                                                                                                    
Get-Help Get-ExecutionPolicy                                                                                                                                                                                                           
Get-Help Set-ExecutionPolicy                                                                                                                                                                                                           
clea                                                                                                                                                                                                                                   
clear                                                                                                                                                                                                                                  
function add { 1+3 }                                                                                                                                                                                                                   
add                                                                                                                                                                                                                                    
function paramshow {$args}                                                                                                                                                                                                             
paramshow "hi"                                                                                                                                                                                                                         
function paramadd {$args[0] + $args[1]}                                                                                                                                                                                                
paramadd 3 7                                                                                                                                                                                                                           
clear                                                                                                                                                                                                                                  
function newfunction 9$num1, 4num2) {$num1 * $num2}                                                                                                                                                                                    
function newfunction ($num1, $num2) {$num1 * $num2}                                                                                                                                                                                    
newfunction 2 6                                                                                                                                                                                                                        
function psfunc ($param1, $param2) {$param1}                                                                                                                                                                                           
posfunc -param1 2 -param2 4                                                                                                                                                                                                            
function posfunc ($param1, $param2) {$param1}                                                                                                                                                                                          
posfunc -param1 2 -param2 4                                                                                                                                                                                                            
posfunc 2 4                                                                                                                                                                                                                            
posfunc -param2 4 -param1 4                                                                                                                                                                                                            
function varparams ($a, $b) {...                                                                                                                                                                                                       
varparams "Hi" "Bye"                                                                                                                                                                                                                   
varparams "Hi" "Bye" "Hi Again"                                                                                                                                                                                                        
$args                                                                                                                                                                                                                                  
function variableparams($a, $b){...                                                                                                                                                                                                    
variableparams "Hi" "Hello" "Merhaba"                                                                                                                                                                                                  
variableparams "Hi" "Hello" "Merhaba" "Hola"                                                                                                                                                                                           
function addint ([int]$a, pint]$b) {$a + $b}                                                                                                                                                                                           
function addint ([int]$a, [int]$b) {$a + $b}                                                                                                                                                                                           
addint 3 4                                                                                                                                                                                                                             
clear                                                                                                                                                                                                                                  
function defaultval (#a = 32, $b) {...                                                                                                                                                                                                 
}                                                                                                                                                                                                                                      
function defaultval ($a = 32, $b) {...                                                                                                                                                                                                 
defaultval 52                                                                                                                                                                                                                          
defaultval                                                                                                                                                                                                                             
function switchable ($a, $b, [switch]$flip){...                                                                                                                                                                                        
switchable 1 2                                                                                                                                                                                                                         
switchable 1 2 -flip                                                                                                                                                                                                                   
$output = switchable 1 2                                                                                                                                                                                                               
$output                                                                                                                                                                                                                                
$var1 = 33                                                                                                                                                                                                                             
function fun1 ($var1 = 22) {$var1}                                                                                                                                                                                                     
$var1                                                                                                                                                                                                                                  
fun1                                                                                                                                                                                                                                   
function fun2 ($var1 = 11) {$var1}                                                                                                                                                                                                     
fun2                                                                                                                                                                                                                                   
$var1                                                                                                                                                                                                                                  
function fun2 ($var = 11111) {$var}                                                                                                                                                                                                    
fun2                                                                                                                                                                                                                                   
ls function\                                                                                                                                                                                                                           
ls function                                                                                                                                                                                                                            
ls function:                                                                                                                                                                                                                                                                                                                                              
function advencedfunction...                                                                                                                      
function advencedfunction...                                                                                                                      
. '.\Users\hfaka\Desktop\pentester Powershell\advencedfunction.ps1'                                                                               
advencedfunction                                                                                                                                  
55 | advencedfunction -b 2                                                                                                                        
C:\Users\hfaka\Desktop\pentester Powershell\advencedfunction.ps1                                                                                  
advencedfunction -a 1                                                                                                                             
advencedfunction -b 1                                                                                                                             
advencedfunction -a $null -b 1                                                                                                                    
history
                                                                               
. .\advencedscript.ps1                                                                                                                            
. .\advencedscript.ps1                                                                                                                            
Show-AdvencedScript -FilePath C:\procs.txt                                                                                                        
. .\advencedscript.ps1                                                                                                                            
Show-AdvencedScript -FilePath C:\procs.txt                                                                                                        
Show-AdvencedScript -FilePath C:\procs.txt -Verbose                                                                                               
Show-AdvencedScript -FilePath C:\loc.txt -Verbose                                                                                                 
Show-AdvencedScript -FilePath C:\loc.txt -WhatIf                                                                                                  
Show-AdvencedScript -FilePath C:\loc.txt -WhatIf                                                                                                  
. .\advencedscript.ps1                                                                                                                            
Show-AdvencedScript -FilePath C:\loc.txt -WhatIf                                                                                                  
Show-AdvencedScript -FilePath C:\list.txt -WhatIf                                                                                                 
Show-AdvencedScript -FilePath C:\list.txt -Confirm                                                                                                
. .\advencedscript.ps1                                                                                                                            
Show-AdvencedScript -FilePath C:\loc.txt -WhatIf                                                                                                  
Get-Module -ListAvailable                                                                                                                         
Get-Module -ListAvailable                                                                                                                         
Get-Module -ListAvailable                                                                                                                         
Get-Module -ListAvailable                                                                                                                         
$env:PSModulePath                                                                                                                                                                                                                                                                            
copy .\advencedfunction.ps1 .\advencedfunction.psm1                                                                                               
Import-Module .\advencedfunction.psm1                                                                                                             
Get-Command -Module advencedfunction                                                                                                              
Import-Module .\advencedfunction.psm1 -Verbose                                                                                                    
advencedfunction C:\bootmgr                                                                                                                       
Import-Module .\advencedfunction.psm1                                                                                                                                                                                                                                      
Remove-Module advencedfunction                                                                                                                    
Import-Module .\advencedfunction.psm1 -Verbose                                                                                                    
Test-FileExistence C:\bootmgr                                                                                                                     
New-ModuleManifest .\advencedscript.psd1                                                                                                                                                                                                              
Get-Command -CommandType Cmdlet | Where-Object {$_.Parameters.Keys -contains 'ComputerName' -and $_.Parameters.Keys -contains 'Credential' -and...
$_.Parameters.Keys                                                                                                                                
Get-Command -CommandType Cmdlet | Where-Object {$_.Parameters.Keys -contains 'ComputerName' -and $_.Parameters.Keys -contains 'Credential' -and...
Get-Command -CommandType Cmdlet | Get-Member                                                                                                      
foreach ($pc in ('hfakar', 'localhost', 'google.com')) {Test-Connection $pc}                                                                                                                                                      


